### ISSUE TITLE
Model check point request

### ISSUE THREAD

**Issue by YanghaoZYH** [PKU-ML/CFA#1]
Dear authors,

Could you provide the trained check point for the proposed CFA?

Or alternatively, can you provide the proper training script to reproduce the results in the paper? 

Many thanks

**Comment by weizeming** [comment]
Dear Yanghao,
Sorry for replying late.
We have uploaded the trained checkpoints to Google drive and the url is available on the README page. 
Additionally, the training and evaluation script will be available soon.
Best,
